apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-service-backend-deployment
  namespace: todo-service
  labels:
    todo-service: backend
    version: 1.3-SNAPSHOT
spec:
  replicas: 3
  selector:
    matchLabels:
      todo-service: backend
  template:
    metadata:
      labels:
        todo-service: backend
    spec:
      containers:
        - name: backend
          image: maxweis/todo-service:1.0-SNAPSHOT
          livenessProbe:
            initialDelaySeconds: 2
            periodSeconds: 5
            httpGet:
              path: /health/live
              port: api
          readinessProbe:
            initialDelaySeconds: 10
            httpGet:
              path: /health/ready
              port: api
          ports:
            - containerPort: 8080
              name: api